language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
   - sudo apt-get update -qq
install:
   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
   - sudo apt-get install -y -qq python-numpy python-scipy libzmq3-dev
   - LANG=C pip install pyzmq  --user
   - LANG=C pip install dsltools  --user
   - LANG=C pip install cython  --user
   - LANG=C pip install parakeet  --user
   - LANG=C pip install scikit-learn  --user
   - LANG=C pip install traits  --user
   - LANG=C python setup.py develop  --user
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
   - $CXX --version
   - gcc  --version
   - nosetests -v --logging-level=INFO --logging-clear-handlers --logging-format='%(filename)s:%(lineno)s [%(funcName)s] %(message)s'
