language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
   - sudo apt-get update -qq
install:
   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
   - sudo apt-get install g++-4.8 -y
   - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
   - sudo apt-get install -y -qq python-numpy python-scipy libzmq3-dev
   - LANG=C pip install pyzmq
   - LANG=C pip install dsltools
   - LANG=C pip install cython
   - LANG=C pip install parakeet
   - LANG=C pip install scikit-learn
   - LANG=C pip install traits
   - LANG=C python setup.py develop
script: nosetests -v --logging-level=INFO --logging-clear-handlers --logging-format='%(filename)s:%(lineno)s [%(funcName)s] %(message)s'
